<h1 align=center><font size = 5 color=black>Computer Vision Assignment-1</font></h1>
<hr style="border:0.01px solid black"> </hr>

**Name** : Rishabh Bhatt   
**Part-1** : Python Basics    
**Submission** : Feb 01, 2022

### Basic data types

In [1]:
# Integers
x = 3
out = '{0:<%d} : {1}'%(30)

# print the type of x
print(out.format('Type of x', str(type(x))))

# Addition : add 1 to x and print the result
print(out.format('Adding 1 to x', x+1))

# Subtraction; subtract 1 from x and print the result
print(out.format('Subtracting 1 from x', x))

# Multiplication; multiply x with 2 and print the result
print(out.format('Multiplying x with 2', x))

# Exponentiation; print the square of x
print(out.format('Square of x', x**2))

Type of x                      : <class 'int'>
Adding 1 to x                  : 4
Subtracting 1 from x           : 3
Multiplying x with 2           : 3
Square of x                    : 9


In [2]:
#floats
y = 2.5
#print the type of y
print(out.format('Type of y', str(type(y))))

#use operator *= to double the value of y and print y 
y *= 2
print(out.format('Double of y', y))

#use operator += to add 3 to y and print y 
y += 3
print(out.format('Add 3 to y', y))

Type of y                      : <class 'float'>
Double of y                    : 5.0
Add 3 to y                     : 8.0


In [3]:
# Strings
s = "hello"

# Capitalize the above string and print it
print(out.format('Capitalized',s.capitalize()))

# Convert the string to uppercase and print it
s_new = s.upper()
print(out.format('Upper Case',s_new))
      
# Right-justify the string, padding with 2 spaces print it;
print(out.format('Right Justified with padding',s.rjust(2+len(s))))

# Center the string, padding with 2 spaces print it;
print(out.format('Center Justified with padding',s.center(2+len(s))))

# Replace all instances of letter l  with "(ell)" and print it;
print(out.format('Replaced',s.replace('l','(ell)')))

st = " world "
# Strip leading and trailing whitespace in the above string and print
print(out.format('Stripped',st.strip()))

Capitalized                    : Hello
Upper Case                     : HELLO
Right Justified with padding   :   hello
Center Justified with padding  :  hello 
Replaced                       : he(ell)(ell)o
Stripped                       : world


### Containers

In [4]:
#Lists
#create a list of first five natural numbers
list1 = [1,2,3,4]
print(out.format('List1',list1))
#change the 3rd element to "foo" and print list1
list1[2] = 'foo'
print(out.format('List1 updated',list1))
list2 = ["bar"]
#append list2 to list1 and print the result
list1 += list2
print(out.format('List1 + List2',list1))
#add list2 to list1 using extend and print the result
list1.extend(list2)
print(out.format('List1 extended',list1))
#remove last element in list1 using pop and print list1
list1.pop()
print(out.format('List1 poped',list1))

List1                          : [1, 2, 3, 4]
List1 updated                  : [1, 2, 'foo', 4]
List1 + List2                  : [1, 2, 'foo', 4, 'bar']
List1 extended                 : [1, 2, 'foo', 4, 'bar', 'bar']
List1 poped                    : [1, 2, 'foo', 4, 'bar']


In [5]:
#Slicing 
nums = list(range(5))
print(out.format('Nums',nums))
#print a slice from index 2 to 4 (exclusive)
print(out.format('Nums slice 2 to 4 (exclusive)',nums[2:4]))
#print a slice from index 2 to 4 (exclusive)
print(out.format('Nums slice 2 to 4 (exclusive)',nums[2:4]))
# Slice indices can be negative; 
print(out.format('Nums negative slice',nums[:-3]))
# Assign the [8,9] new list to a slice from index 2 to 4 (exclusive)
nums[2:4] = [8,9]
print(out.format('Nums updated',nums))

Nums                           : [0, 1, 2, 3, 4]
Nums slice 2 to 4 (exclusive)  : [2, 3]
Nums slice 2 to 4 (exclusive)  : [2, 3]
Nums negative slice            : [0, 1]
Nums updated                   : [0, 1, 8, 9, 4]


In [6]:
#Loops
nums = [0, 1, 2, 3, 4]
print(out.format('Nums',nums))
squares = []
# append squares of each element in nums to squares using for loop
for num in nums: 
    squares.append(num**2)

print(out.format('Square',squares))
####
animals = ['cat', 'dog', 'monkey']
print(out.format('Animals',animals))
#print index and elements in the list using enumerate and for loop
print(out.format('Enumerating',''))
print('-'*70)
for i,val in enumerate(animals):
    print (i,':',val)
print('-'*70)
#print squares of even numbers using list comprehensions
nums = [0, 1, 2, 3, 4]
print(out.format('Nums',nums))
even_squares = [(i**2) for i in nums if i%2 == 0]
print(out.format('Square of even numbers',even_squares))

Nums                           : [0, 1, 2, 3, 4]
Square                         : [0, 1, 4, 9, 16]
Animals                        : ['cat', 'dog', 'monkey']
Enumerating                    : 
----------------------------------------------------------------------
0 : cat
1 : dog
2 : monkey
----------------------------------------------------------------------
Nums                           : [0, 1, 2, 3, 4]
Square of even numbers         : [0, 4, 16]


In [7]:
#Dictionaries
#create a dictionary with keys = (cat, dog) and items = (cute,furry)
keys = ('cat','dog')
items = ('cute','furry')
d = dict(zip(keys,items))
print(out.format('Dictionary',d))

#set an entry {fish:wet}
d['fish'] = 'wet'
print(out.format('Dictionary fish added',d))
#remove the entry with key= cat 
del d['cat']
print(out.format('Dictionary cat removed',d))

# Get an element with a default;
print(out.format('Get monkey',d.get('monkey', 'N/A')))

# get an element with key= fish and print it
print(out.format('Get fish',d.get('fish', 'N/A')))

#print all keys in dictionary
print(out.format('Keys of Dict',list(d.keys())))
#print all items in dictionary
print(out.format('Keys of Dict',list(d.items())))

Dictionary                     : {'cat': 'cute', 'dog': 'furry'}
Dictionary fish added          : {'cat': 'cute', 'dog': 'furry', 'fish': 'wet'}
Dictionary cat removed         : {'dog': 'furry', 'fish': 'wet'}
Get monkey                     : N/A
Get fish                       : wet
Keys of Dict                   : ['dog', 'fish']
Keys of Dict                   : [('dog', 'furry'), ('fish', 'wet')]


In [8]:
#sets 
#create a set with elements cat, dog and fish
s = {'cat','dog','fish'}
print(out.format('Set',s))
#add monkey to the set
s.add('monkey')
print(out.format('Set with monkey added',s))
#remove fish from the set 
s.remove('fish')
print(out.format('Set with fish removed',s))
#checks if an element is in the set
print(out.format('If an element is in the set',('fish' in animals)))

Set                            : {'cat', 'dog', 'fish'}
Set with monkey added          : {'cat', 'dog', 'fish', 'monkey'}
Set with fish removed          : {'cat', 'dog', 'monkey'}
If an element is in the set    : False


### Numpy

In [9]:
#importing the numpy package 
import numpy as np
b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
#print the shape of the array
print (b.shape,'\n')
#print an array of all zeros of shape(2,2)
print (np.zeros((2,2)),'\n')
#print an array of all ones of shape(1,2)
print (np.ones((1,2)),'\n')
#print an array of shape (3,3) with all elements in array = 7
print (np.full((3,3),7),'\n')
#print an array filled with random values of shape (2,2)
print (np.random.rand(2,2),'\n')

(2, 3) 

[[0. 0.]
 [0. 0.]] 

[[1. 1.]] 

[[7 7 7]
 [7 7 7]
 [7 7 7]] 

[[0.14667414 0.20298965]
 [0.17098709 0.9699472 ]] 



In [10]:
#ARRAY INDEXING
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
#print(a)

# Use slicing to print out the subarray consisting of the first 2 rows and columns 1 and 2;
print (a[:2,[1,2]])
print ()
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
b = np.array([0, 2, 0, 1])

# print one element from each row of a using the indices in b
print (a [list(range(b.shape[0])),[0,2,0,1]])
print ()

# add 10 to one element from each row of a using the indices in b
a [list(range(b.shape[0])),[0,2,0,1]] += 10
print (a)

[[2 3]
 [6 7]]

[ 1  6  7 11]

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [11]:
#Boolean array indexing
a = np.array([[1,2], [3, 4], [5, 6]])

#Print a numpy array of Booleans where elements of a are bigger than 2 ,shape=(3,2)
print (a>2)
print ()

#a rank 1 array consisting of the elements of a that are bigger than 2
print (a[a>2])
print ()

x = np.array([1, 2]) 
#print data type of the array
print (type(a))
print (a.dtype)

#create an array [[1,2],[3,4]] with data type int64.
b = np.array([[1,2],[3,4]], dtype='int64')
print (b)

[[False False]
 [ True  True]
 [ True  True]]

[3 4 5 6]

<class 'numpy.ndarray'>
int32
[[1 2]
 [3 4]]


In [12]:
#Array math
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

#print elementwise addition using numpy function
print (np.add(x,y))
print ()

#print elementwise difference using numpy function
print (np.subtract(x,y))
print ()

#print elementwise multiplication using numpy function
print (np.multiply(x,y))
print ()

#print elementwise division using numpy function
print (np.divide(x,y))
print ()

#print elementwise square root using numpy function
print (np.sqrt(x))
print (np.sqrt(y))

[[ 6.  8.]
 [10. 12.]]

[[-4. -4.]
 [-4. -4.]]

[[ 5. 12.]
 [21. 32.]]

[[0.2        0.33333333]
 [0.42857143 0.5       ]]

[[1.         1.41421356]
 [1.73205081 2.        ]]
[[2.23606798 2.44948974]
 [2.64575131 2.82842712]]


In [13]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

#print Inner product of vectors
print (np.inner(v,w))
print ()

#print matrix / vector product of x and v 
print (np.matmul(x,v))
print ()

#print matrix / vector product of x and y 
print (np.matmul(x,y))

219

[29 67]

[[19 22]
 [43 50]]


In [14]:
x = np.array([[1,2],[3,4]])
#print sum of all elements in array
print (x.sum())
#print sum of elements in each row
print (x.sum(axis=1))
#print sum of elements in each column
print (x.sum(axis=0))

10
[3 7]
[4 6]


In [15]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])

#Create an empty matrix with the same shape as x and print
y = np.empty(x.shape)
print (y)
print ()

# create an array y by adding  the vector v to each row of the matrix x with an explicit loop 
#print y
y = x.copy()
for i in range(y.shape[0]):
    y[i] += v
print (y)
print () 

#Add v to each row of x using broadcasting
#store the result in matrix y and print y
y_brd = x+v
print (y_brd)

[[1.59265468e-311 3.16202013e-322 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 6.23757186e+174]
 [3.53781476e-061 8.24381023e-043 3.45115315e-032]
 [6.17863904e-042 4.27407215e-033 3.40559164e+175]]

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [16]:
v = np.array([1,2,3])  
w = np.array([4,5])
#reshape v to(3,1) using numpy function and print it
v = np.reshape(v,(3,1))
print (v)

[[1]
 [2]
 [3]]


<hr style="border:0.01px solid black"> </hr>